# coding: utf-8

"""
    Literature Graph Service

    Fetch paper and author data from the Semantic Scholar corpus

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import s2cholar
from s2cholar.models.error404 import Error404
from s2cholar.rest import ApiException

"""Error404 unit test stubs"""

def testError404(self):
    """Test Error404"""
    # FIXME: construct object with mandatory attributes with example values
    # model = s2cholar.models.error404.Error404()
    pass
