# coding: utf-8

"""
    Literature Graph Service

    Fetch paper and author data from the Semantic Scholar corpus

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import s2cholar
from s2cholar.models.full_paper import FullPaper
from s2cholar.rest import ApiException


"""FullPaper unit test stubs"""

def testFullPaper(self):
    """Test FullPaper"""
    # FIXME: construct object with mandatory attributes with example values
    # model = s2cholar.models.full_paper.FullPaper()
    pass

