# coding: utf-8

"""
    Literature Graph Service

    Fetch paper and author data from the Semantic Scholar corpus  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import s2cholar
from s2cholar.api.author_api import AuthorApi  # noqa: E501
from s2cholar.rest import ApiException


class TestAuthorApi(unittest.TestCase):
    """AuthorApi unit test stubs"""

    def setUp(self):
        self.api = s2cholar.api.author_api.AuthorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_graph_get_author(self):
        """Test case for get_graph_get_author

        Details about an author  # noqa: E501
        """
        pass

    def test_get_graph_get_author_papers(self):
        """Test case for get_graph_get_author_papers

        Details about an author's papers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
