# coding: utf-8

"""
    Literature Graph Service

    Fetch paper and author data from the Semantic Scholar corpus  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import s2cholar
from s2cholar.models.embedding import Embedding  # noqa: E501
from s2cholar.rest import ApiException


class TestEmbedding(unittest.TestCase):
    """Embedding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmbedding(self):
        """Test Embedding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = s2cholar.models.embedding.Embedding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
