# coding: utf-8

# flake8: noqa

"""
    Literature Graph Service

    Fetch paper and author data from the Semantic Scholar corpus  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from s2cholar.api.author_api import AuthorApi
from s2cholar.api.paper_api import PaperApi

# import ApiClient
from s2cholar.api_client import ApiClient
from s2cholar.configuration import Configuration
# import models into sdk package
from s2cholar.models.author import Author
from s2cholar.models.author_batch import AuthorBatch
from s2cholar.models.author_info import AuthorInfo
from s2cholar.models.author_with_papers import AuthorWithPapers
from s2cholar.models.base_paper import BasePaper
from s2cholar.models.citation import Citation
from s2cholar.models.citation_batch import CitationBatch
from s2cholar.models.citation_citing_paper import CitationCitingPaper
from s2cholar.models.embedding import Embedding
from s2cholar.models.error400 import Error400
from s2cholar.models.error404 import Error404
from s2cholar.models.full_paper import FullPaper
from s2cholar.models.paper_batch import PaperBatch
from s2cholar.models.paper_info import PaperInfo
from s2cholar.models.paper_search_batch import PaperSearchBatch
from s2cholar.models.paper_with_links import PaperWithLinks
from s2cholar.models.reference import Reference
from s2cholar.models.reference_batch import ReferenceBatch
from s2cholar.models.reference_cited_paper import ReferenceCitedPaper
